"""
knowledge.py
Mechanical/production/QA knowledge commands (/cnc, /vmc, /qa, /gdt, etc.).
Content is generated by Claude on demand rather than hardcoded, then cached
to disk for a day per-topic so repeated requests don't re-hit the API.
"""

import json
import os
import time
from typing import Optional

from config import settings
from logger import get_logger
from utils import ask_claude, hash_text

log = get_logger(__name__)

CACHE_TTL_SECONDS = 24 * 60 * 60

TOPICS = {
    "cnc": "CNC machining fundamentals: axes, controllers, G-code/M-code basics, common a